### ISSUE TITLE
Upgrade Yarn from v1 to v4

### ISSUE THREAD

**Issue by mcmire** [MetaMask/eth-block-tracker#285]
This repo is using Yarn v1, but the module template uses Yarn v4. We should align this repo so that it is easier to maintain going forward.

## Acceptance Criteria

- `.yarnrc` is replaced with `.yarnrc.yml`
- `packageManager` is set to `yarn@4.X.Y` replacing `X` and `Y` as necessary to match latest Yarn version
- `.yarn/plugins/@yarnpkg/plugin-allow-scripts.cjs` is added (if `@lavamoat/allow-scripts` is present)
- `.yarnrc.yml` lists `allow-scripts` plugin in `plugins` (if `@lavamoat/allow-scripts` is present)
- GitHub workflows that rely on dependencies to be installed must have:
    ``` yaml
    - name: Install Corepack via Node
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
    - name: Install Yarn
      run: corepack enable
    - name: Install Node.js ${{ matrix.node-version }} and restore Yarn cache
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Install dependencies via Yarn
      run: yarn --immutable
    ```
- `yarn.config.cjs` must be present

## Suggestions/Considerations

Running `yarn set version stable` will take care of some of the steps above automatically.
